### ISSUE TITLE
Typo in node.js error codes?

### ISSUE THREAD

**Issue by bpasero** [fabiospampinato/stubborn-fs#1]
Hi @fabiospampinato,

in https://github.com/fabiospampinato/stubborn-fs/blob/e85c98601fc805eff8d81374a1894a7ab31eefc5/src/handlers.ts#L38 I wonder if `EACCESS` needs to be `EACCES` instead? I also never heard about `EACCS`.

**Comment by fabiospampinato** [comment]
Oh yeah, it looks like it. I don't exactly remember where all those strings come from, maybe `EACCESS` was a typo on my end, `EACCS` is weird I can't find matches for it, but I doubt I made it up 🤔 

Anyway, deleting the rest seems a bit risky, and keeping them in the list should be fine, so I just added `EACCES` to the list in v1.2.5, thank you ❤️
